# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme: fongandrew/hydeout




# Setup
title:            Hanting Ye
tagline:          'Damon'
description:      'PhD student&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<a href="https://www.tudelft.nl/ewi/over-de-faculteit/afdelingen/software-technology/embedded-and-networked-systems/" target="_blank">ENS Group</a>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<a href="https://www.tudelft.nl/en/" target="_blank">TU Delft</a>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<em>Email</em>: <a href="mailto: H.Ye-1@tudelft.nl" target="_blank">H.Ye&#8288;-&#8288;1@tudelft.nl</a>&emsp;<em>Office</em>: 2.W.860, West 2nd floor, <a href="https://iamap.tudelft.nl/poi/elektrotechniek-wiskunde-informatica/" target="_blank">Building 28</a>&emsp;&emsp;&emsp;<em>Address</em>: Van Mourik Broekmanweg 6, 2628 XE Delft, The Netherlands'
url:              https://hantingye.github.io



author:
  name:           'Hanting Ye'
  url:            https://hantingye.github.io/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  flase
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname:      hydeout

google_analytics: UA-100461102-1

# Used for Hydeout's own Github page. Feel free to remove for your
# own fork.

email: H.Ye-1@tudelft.nl
linkedin: https://www.linkedin.com/in/hanting-ye-b8585b114/

hydeout:
  repo:             https://github.com/hantingye

