# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme: fongandrew/hydeout


# Setup
title:            Hanting Ye
tagline:          'Damon'
description:      'PhD student at the <a href="https://www-tudelft-nl.tudelft.idm.oclc.org/ewi/over-de-faculteit/afdelingen/software-technology/embedded-and-networked-systems" target="_blank">Embedded and Networked Systems Group</a>, <a href="https://www.tudelft.nl/en/" target="_blank">Delft University of Technology</a>.'
url:              https://hantingye.github.io
