# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme: fongandrew/hydeout




# Setup
title:            Hanting Ye
tagline:          'Damon'
description:      '<p align=center style="font-size:0.7rem;">PhD candidate <br><a href="https://www.tudelft.nl/en/" target="_blank">TU Delft</a></p>'  
url:              https://hantingye.github.io



author:
  name:           'Hanting Ye'
  url:            https://hantingye.github.io/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname:      hantingye

google_analytics: 'G-6HGXJBGQRV'

# Used for Hydeout's own Github page. Feel free to remove for your
# own fork.

email: H.Ye-1@tudelft.nl
linkedin: https://www.linkedin.com/in/hanting-ye/
scholar: https://scholar.google.com/citations?user=MGb2RFcAAAAJ

hydeout:
  repo:             https://github.com/hantingye
