# Dependencies
markdown:         kramdown
remote_theme:     hydeout
highlighter:      rouge


# Setup
title:            Hanting Ye
tagline:          'Damon'
description:      'PhD student at the <a href="https://www-tudelft-nl.tudelft.idm.oclc.org/ewi/over-de-faculteit/afdelingen/software-technology/embedded-and-networked-systems" target="_blank">Embedded and Networked Systems Group</a>, <a href="https://www.tudelft.nl/en/" target="_blank">Delft University of Technology</a>.'
url:              https://hantingye.github.io
baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Hanting Ye'
  url:            https://hantingye.github.io/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
