# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme: fongandrew/hydeout


# Setup
title:            Hanting Ye
tagline:          'Damon'
description:      'PhD student at the <a href="https://www-tudelft-nl.tudelft.idm.oclc.org/ewi/over-de-faculteit/afdelingen/software-technology/embedded-and-networked-systems" target="_blank">Embedded and Networked Systems Group</a>, <a href="https://www.tudelft.nl/en/" target="_blank">Delft University of Technology</a>.'
url:              https://hantingye.github.io


author:
  name:           'Hanting Ye'
  url:            https://hantingye.github.io/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname:      hydeout

google_analytics: UA-100461102-1

# Used for Hydeout's own Github page. Feel free to remove for your
# own fork.
hydeout:
  version:          4.2.0
  repo:             https://github.com/fongandrew/hydeout
